const express = require('express');
const router = express.Router();

const adminRoutes = require('../modules/admin/admin.routes.js');
const aiRoutes = require('../modules/ai/ai.routes.js');
const assignmentRoutes = require('../modules/learning/assignment.routes.js');
const authRoutes = require('../modules/auth/auth.routes.js');
const categoryRoutes = require('../modules/courses/category.routes.js');
const chatRoutes = require('../modules/community/chat.routes.js');
const contactRoutes = require('../modules/contact/contact.routes.js');
const documentRoutes = require('../modules/documents/document.routes.js');
const followRoutes = require('../modules/community/follow.routes.js');
const codingProblemRoutes = require('../modules/practice/codingProblem.routes.js');
const codingSubmissionRoutes = require('../modules/practice/codingSubmission.routes.js');
const courseRoutes = require('../modules/courses/course.routes.js');
const discussionRoutes = require('../modules/community/discussion.routes.js');
const enrollmentRoutes = require('../modules/learning/enrollment.routes.js');
const lessonRoutes = require('../modules/courses/lesson.routes.js');
const moduleRoutes = require('../modules/courses/module.routes.js');
const notificationRoutes = require('../modules/community/notification.routes.js');
const progressRoutes = require('../modules/learning/progress.routes.js');
const reviewRoutes = require('../modules/learning/review.routes.js');
const submissionRoutes = require('../modules/learning/submission.routes.js');
const testCaseRoutes = require('../modules/practice/testCase.routes.js');
const resourceRoutes = require('../modules/courses/resource.routes.js');
const reportRoutes = require('../modules/admin/report.routes.js');
const userRoutes = require('../modules/users/user.routes.js');

router.use('/admin', adminRoutes);
router.use('/ai', aiRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/auth', authRoutes);
router.use('/categories', categoryRoutes);
router.use('/chat', chatRoutes);
router.use('/contact', contactRoutes);
router.use('/follows', followRoutes);
router.use('/problems', codingProblemRoutes);
router.use('/coding-submissions', codingSubmissionRoutes);
router.use('/courses', courseRoutes);
router.use('/documents', documentRoutes);
router.use('/discussions', discussionRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/lessons', lessonRoutes);
router.use('/modules', moduleRoutes);
router.use('/notifications', notificationRoutes);
router.use('/progress', progressRoutes);
router.use('/reviews', reviewRoutes);
router.use('/submissions', submissionRoutes);
router.use('/testcases', testCaseRoutes);
router.use('/resources', resourceRoutes);
router.use('/users', userRoutes);
router.use('/', reportRoutes);

module.exports = router;
