import React, { useState, useRef } from 'react';
import { Upload, Image as ImageIcon, Shield, Eraser, CheckCircle2, AlertTriangle, Download, Loader2 } from 'lucide-react';
import { Card } from '@/components/ui';
import toast from "react-hot-toast";

export default function AIImageTool() {
  const [file, setFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [isVerifying, setIsVerifying] = useState(false);
  const [isStripping, setIsStripping] = useState(false);
  const [result, setResult] = useState<any>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files.length > 0) {
      const selectedFile = e.target.files[0];
      setFile(selectedFile);
      setPreviewUrl(URL.createObjectURL(selectedFile));
      setResult(null);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      const selectedFile = e.dataTransfer.files[0];
      if (selectedFile.type.startsWith('image/')) {
        setFile(selectedFile);
        setPreviewUrl(URL.createObjectURL(selectedFile));
        setResult(null);
      } else {
        toast.error('Please upload an image file');
      }
    }
  };

  const handleVerify = async () => {
    if (!file) return;
    setIsVerifying(true);
    setResult(null);

    const formData = new FormData();
    formData.append('image', file);

    try {
      const response = await fetch('http://localhost:5005/api/ai/image/verify', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${localStorage.getItem('token')}`,
        },
        body: formData,
      });

      if (!response.ok) throw new Error('Verification failed');
      const data = await response.json();
      setResult(data);
      if (data.isAiGenerated) {
        toast('AI signatures detected in metadata', { icon: '⚠️' });
      } else {
        toast.success('No AI signatures found in metadata');
      }
    } catch (error) {
      toast.error('Failed to verify image');
    } finally {
      setIsVerifying(false);
    }
  };

  const handleStripMetadata = async () => {
    if (!file) return;
    setIsStripping(true);

    const formData = new FormData();
    formData.append('image', file);

    try {
      const response = await fetch('http://localhost:5005/api/ai/image/strip-metadata', {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${localStorage.getItem('token')}`,
        },
        body: formData,
      });

      if (!response.ok) throw new Error('Failed to strip metadata');

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.style.display = 'none';
      a.href = url;
      a.download = `clean_${file.name}`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      toast.success('Metadata stripped and image downloaded!');
    } catch (error) {
      toast.error('Failed to strip metadata');
    } finally {
      setIsStripping(false);
    }
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 text-slate-100">
      <div className="mb-10 text-center">
        <h1 className="text-4xl font-bold text-white mb-4 flex items-center justify-center gap-3">
          <Shield className="w-10 h-10 text-blue-400" /> AI Image Verifier
        </h1>
        <p className="text-slate-400 max-w-2xl mx-auto text-lg">
          Detect if an image was generated by AI using its embedded metadata (EXIF/XMP). You can also completely strip all metadata to protect your privacy.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Upload Section */}
        <Card className="!rounded-3xl !p-8 bg-slate-900/50 border-slate-800 backdrop-blur-sm">
          <div
            className={`border-2 border-dashed rounded-2xl p-10 flex flex-col items-center justify-center text-center transition-all cursor-pointer ${
              file ? 'border-blue-500/50 bg-blue-500/5' : 'border-slate-700 hover:border-blue-500 hover:bg-slate-800/50'
            }`}
            onDragOver={(e) => e.preventDefault()}
            onDrop={handleDrop}
            onClick={() => fileInputRef.current?.click()}
          >
            <input
              type="file"
              ref={fileInputRef}
              className="hidden"
              accept="image/*"
              onChange={handleFileChange}
            />
            
            {previewUrl ? (
              <div className="relative w-full aspect-video rounded-xl overflow-hidden mb-4 border border-slate-700 shadow-lg">
                <img src={previewUrl} alt="Preview" className="w-full h-full object-cover" />
                <div className="absolute inset-0 bg-black/40 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity">
                  <span className="text-white font-medium flex items-center gap-2">
                    <Upload className="w-5 h-5" /> Change Image
                  </span>
                </div>
              </div>
            ) : (
              <div className="w-20 h-20 rounded-full bg-slate-800 flex items-center justify-center mb-4 text-slate-400">
                <ImageIcon className="w-10 h-10" />
              </div>
            )}
            
            <h3 className="text-xl font-bold text-white mb-2">
              {file ? file.name : 'Upload an Image'}
            </h3>
            <p className="text-slate-400 text-sm">
              {file ? `${(file.size / 1024 / 1024).toFixed(2)} MB` : 'Drag and drop or click to browse'}
            </p>
          </div>
        </Card>

        {/* Actions & Results Section */}
        <div className="space-y-6">
          <Card className="!rounded-3xl !p-8 bg-slate-900/50 border-slate-800 flex flex-col justify-center h-full gap-6">
            <h3 className="text-2xl font-bold text-white">Analysis & Actions</h3>
            
            <button
              onClick={handleVerify}
              disabled={!file || isVerifying || isStripping}
              className="w-full py-4 px-6 rounded-xl font-bold text-white shadow-lg shadow-blue-600/20 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 flex items-center justify-center gap-3"
            >
              {isVerifying ? (
                <><Loader2 className="w-5 h-5 animate-spin" /> Verifying Metadata...</>
              ) : (
                <><Shield className="w-5 h-5" /> Verify AI Signatures</>
              )}
            </button>

            <button
              onClick={handleStripMetadata}
              disabled={!file || isVerifying || isStripping}
              className="w-full py-4 px-6 rounded-xl font-bold text-white shadow-lg shadow-rose-600/20 bg-slate-800 hover:bg-slate-700 border border-slate-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-300 flex items-center justify-center gap-3"
            >
              {isStripping ? (
                <><Loader2 className="w-5 h-5 animate-spin" /> Stripping Metadata...</>
              ) : (
                <><Eraser className="w-5 h-5 text-rose-400" /> Strip Metadata & Download</>
              )}
            </button>

            {/* Results Display */}
            {result && (
              <div className={`mt-4 p-6 rounded-2xl border ${result.isAiGenerated ? 'bg-amber-500/10 border-amber-500/20' : 'bg-emerald-500/10 border-emerald-500/20'}`}>
                <div className="flex items-start gap-4">
                  {result.isAiGenerated ? (
                    <AlertTriangle className="w-8 h-8 text-amber-400 shrink-0" />
                  ) : (
                    <CheckCircle2 className="w-8 h-8 text-emerald-400 shrink-0" />
                  )}
                  <div>
                    <h4 className={`text-lg font-bold mb-1 ${result.isAiGenerated ? 'text-amber-400' : 'text-emerald-400'}`}>
                      {result.isAiGenerated ? 'AI Signatures Detected' : 'No AI Signatures Found'}
                    </h4>
                    <p className="text-slate-300 text-sm mb-3">
                      {result.message || (result.isAiGenerated 
                        ? 'We found metadata tags commonly used by AI image generators.' 
                        : 'We could not find any standard AI watermarks in the EXIF/XMP data. Note: this does not guarantee it is a real photo, as metadata can be stripped.')}
                    </p>
                    
                    {result.signatures && result.signatures.length > 0 && (
                      <div className="flex flex-wrap gap-2 mt-3">
                        <span className="text-xs text-slate-400 uppercase font-bold tracking-wider mr-1 py-1">Tags:</span>
                        {result.signatures.map((sig: string) => (
                          <span key={sig} className="px-3 py-1 rounded-full bg-amber-500/20 text-amber-300 text-xs font-semibold">
                            {sig}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              </div>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
}
